const a1 = require('./a1.png');
const a2 = require('./a2.png');
const a3 = require('./a3.png');

export default {
  // a1: require('./a1.png'),
  swiper1Image: require('./Swiper1Image.png'),
  swiper2Image: require('./Swiper2Image.jpg'),
  swiper3Image: require('./Swiper3Image.png'),
  swiper4Image: require('./Swiper4Image.png'),
  swiper5Image: require('./Swiper5Image.png'),
  otpSend: require('./otpSend.png'),
  PasswordChanged: require('./PasswordChanged.png'),
  crossEye: require('./crossEye.png'),
  lock: require('./lock.png'),
  eyeOpen: require('./eyeOpen.png'),
  cross: require('./cross.png'),
  unVerifyPhone: require('./unVerifyPhone.png'),
  VerifyPhone: require('./VerifyPhone.png'),
  cnic: require('./cnic.png'),
  person: require('./person.png'),
  calendar: require('./calendar.png'),
  back: require('./back.png'),
  activeServiceSeeker: require('./ServiceSeeker.png'),
  activeServiceProvider: require('./ServiceProvider.png'),
  activeSkewedRectangle: require('./activeSkewedRectangle.png'),
  inActiveSkewedRectangle: require('./inActiveSkewedRectangle.png'),
  doubleRightArrowGreen: require('./doubleRightArrowGreen.png'),
  DELETE_BADGE: require('./deleteBadge.png'),
  SCAN_DOCUMENT_EXAMPLE: require('./scanDocumentExample.png'),
  HAND_HOLDING_MOBILE: require('./handHoldingMobile.png'),
  CHECK_BADGE: require('./checkBadge.png'),
  FLAG: require('./Flags.png'),
  PROFILE: require('./Profile.png'),
  MECHANIC: require('./mechanic.png'),
  PLUMBER: require('./plumber.png'),
  ELECTRICIAN: require('./electrician.png'),
  Provider: require('./provider.png'),
  VIEW_ALL: require('./view.png'),
  PAINTER: require('./painter.png'),
  CARPENTER: require('./carpenter.png'),
  GARDNER: require('./gardner.png'),
  CLEANER: require('./cleaner.png'),
  TUTOR: require('./tutor.png'),
  CHEF: require('./chef.png'),
  PHOTOGRAPHER: require('./photographer.png'),
  COMP_TECH: require('./computer-technician.png'),
  BABY_SITTER: require('./baby-sitter.png'),
  BAND_MASTER: require('./band.png'),
  DOWN_ARROW: require('./down-arrow.png'),
  DOWN: require('./down.png'),
};
