export default {
  Logo: require('./LogoGreenBlack.png'),
  leftArrow: require('./leftArrow.png'),
  leftArrowWhite: require('./leftArrowWhite.png'),
  BackIcon: require('./BackIcon.png'),
  Phone: require('./Phone.png'),
  Home: require('./Home.png'),
  Chat: require('./Chat.png'),
  Bookings: require('./Bookings.png'),
  Profile: require('./Profile.png'),
  hometabactive: require('./hometabactive.png'),
  hometabinactive: require('./hometabinactive.png'),
  bookingstabactive: require('./bookingstabactive.png'),
  bookingstabinactive: require('./bookingstabinactive.png'),
  messagestabactive: require('./messagestabactive.png'),
  messagestabinactive: require('./messagestabinactive.png'),
  profiletabactive: require('./profiletabactive.png'),
  profiletabinactive: require('./profiletabinactive.png'),
};
