export default {
  Logo: require('./LogoGreenBlack.png'),
  leftArrow: require('./leftArrow.png'),
  leftArrowWhite: require('./leftArrowWhite.png'),
  BackIcon: require('./BackIcon.png'),
  Phone: require('./Phone.png'),
  Home: require('./Home.png'),
  Chat: require('./Chat.png'),
  Bookings: require('./Bookings.png'),
  Profile: require('./Profile.png'),
  HOME_TAB_ACTIVE: require('./hometabactive.png'),
  HOME_TAB: require('./hometabinactive.png'),
  BOOKINGS_TAB_ACTIVE: require('./bookingstabactive.png'),
  BOOKINGS_TAB: require('./bookingstabinactive.png'),
  MESSAGE_TAB_ACTIVE: require('./messagestabactive.png'),
  MESSAGE_TAB: require('./messagestabinactive.png'),
  PROFILE_TAB_ACTIVE: require('./profiletabactive.png'),
  PROFILE_TAB: require('./profiletabinactive.png'),
  CHECK_BLACK: require('./checkBlack.png'),
  CHEVRON: require('./chevron.png'),
};
